/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hotel.booking;

import javax.ws.rs.ApplicationPath;
import javax.ws.rs.core.Application;

@ApplicationPath("/v1")
public class App extends Application {

}
